name: 天气预报推送

on:
  schedule:
    # 每天早上7点执行（UTC 23:00，北京时间+8）
    - cron: '0 23 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  send-weather:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run weather report
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python weather_report.py
